import PDFDocument from "pdfkit";

const PAGE_MARGIN = 40;
const TABLE_PADDING_X = 6;
const TABLE_PADDING_Y = 4;
const HEADER_BG = "#F1F3F5";
const BORDER_COLOR = "#D0D5DD";

const drawTable = (doc, { columns, rows }) => {
  const pageWidth = doc.page.width - PAGE_MARGIN * 2;
  const totalColWidth = columns.reduce((sum, c) => sum + c.width, 0);
  const scale = totalColWidth > pageWidth ? pageWidth / totalColWidth : 1;
  const colWidths = columns.map((c) => Math.floor(c.width * scale));

  let y = doc.y;
  const xStart = PAGE_MARGIN;

  const calcRowHeight = (row, isHeader = false) => {
    const font = isHeader ? "Helvetica-Bold" : "Helvetica";
    doc.font(font).fontSize(10);
    let maxHeight = 0;
    columns.forEach((col, i) => {
      const text = isHeader ? col.label : `${row[col.key] ?? "-"}`;
      const h = doc.heightOfString(text, {
        width: colWidths[i] - TABLE_PADDING_X * 2,
      });
      if (h > maxHeight) maxHeight = h;
    });
    return maxHeight + TABLE_PADDING_Y * 2;
  };

  const drawRow = (row, rowHeight, isHeader = false) => {
    let x = xStart;
    doc.lineWidth(0.5).strokeColor(BORDER_COLOR);
    if (isHeader) {
      doc.rect(
        xStart,
        y,
        colWidths.reduce((a, b) => a + b, 0),
        rowHeight
      ).fill(HEADER_BG);
      doc.fillColor("black");
    }
    columns.forEach((col, i) => {
      doc.rect(x, y, colWidths[i], rowHeight).stroke();
      const text = isHeader ? col.label : `${row[col.key] ?? "-"}`;
      doc
        .font(isHeader ? "Helvetica-Bold" : "Helvetica")
        .fontSize(10)
        .fillColor("black")
        .text(text, x + TABLE_PADDING_X, y + TABLE_PADDING_Y, {
          width: colWidths[i] - TABLE_PADDING_X * 2,
        });
      x += colWidths[i];
    });
    y += rowHeight;
  };

  const drawHeader = () => {
    const headerHeight = calcRowHeight({}, true);
    drawRow({}, headerHeight, true);
  };

  const ensurePage = (heightNeeded) => {
    const bottomLimit = doc.page.height - PAGE_MARGIN;
    if (y + heightNeeded > bottomLimit) {
      doc.addPage();
      y = PAGE_MARGIN;
      drawHeader();
    }
  };

  drawHeader();

  rows.forEach((row) => {
    const rowHeight = calcRowHeight(row, false);
    ensurePage(rowHeight);
    drawRow(row, rowHeight, false);
  });

  doc.moveDown(2);
};

export const generateReportPDF = ({
  res,
  title,
  subtitle,
  columns,
  rows,
}) => {
  const doc = new PDFDocument({ margin: PAGE_MARGIN, size: "A4" });

  res.setHeader("Content-Type", "application/pdf");
  res.setHeader(
    "Content-Disposition",
    `attachment; filename=${title.replace(/\s+/g, "_")}.pdf`
  );

  doc.pipe(res);

  doc.fontSize(18).text(title, { align: "center" });
  if (subtitle) {
    doc.moveDown(0.3);
    doc.fontSize(10).text(subtitle, { align: "center" });
  }
  doc.moveDown(1.2);

  drawTable(doc, { columns, rows });

  doc.fontSize(8).fillColor("#667085").text("Generated by furniOS", {
    align: "center",
  });

  doc.end();
};