
export const REPORT_TYPES = {
  ORDER: "ORDER",
  REVENUE: "REVENUE",
  STOCK: "STOCK",
  PRODUCTION: "PRODUCTION",
  PURCHASE: "PURCHASE",
  ORDER_RETURN: "ORDER_RETURN", // ✅ NEW
  WHOLESALE_QUOTATION: "WHOLESALE_QUOTATION", // ✅ NEW
  PAYMENT: "PAYMENT", // ✅ NEW


};
